version: 2
jobs:
  build:
    working_directory: ~/bixby-cli
    docker:
      image: circleci/node
      steps:
        - checkout
        - run: npm install -g typescript
        - run: npm install
        - run: npm test
        