version: 2
defaults: &defaults
  working_directory: ~/bixby-cli
    docker:
      - image: circleci/node
jobs:
  build:
    <<: *defaults  
    steps:
      - checkout
      - run:
          name: install-typescript
          command: sudo npm install -g typescript
      - run:
          name: install-npm-dependencies
          command: npm install
      - run:
          name: build-project
          command: npm run build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/bixby-cli
      - run:
          name: test
          command: npm test
            