export enum ActionType {
    Fetch,
    Resolver,
    ArchiveLookUp,
    Search,
    Constructor,
    Calculation,
    BeginTransaction,
    UpdateTranaction,
    CancelTransaction,
    Commit,
    RefreshActivity,
    UpdateActivity,
    CancelActivity,
}
